### PR TITLE
Implemented New Cosim Interface

### PR DESCRIPTION
**Pull request by marvin-steinke**
Refactored the code to use `SimWrapper` and `VessimCoordinator` classes to facilitate the initialization and coordination of simulation entities.

Docstrings will follow. I think we can further abstract the `VessimCoordinator.connect` function which I copied from Mosaik for now. I'm also not quite happy with the `Consumer` and `Microgrid` implementations of `SimWrapper` as there are already components from vessim.core with the same name.

## SimWrapper
`SimWrapper` is an ABC for simulation entity wrappers and encapsulates configuration and initialization. It includes methods for setting up simulation entities and their factories, along with argument provision for instantiation.

## VessimCoordinator
The `VessimCoordinator` class orchestrates the co-simulation process by initializing, connecting, and managing simulation entities. It offers methods for adding entities, setting up connections, and executing the co-simulation. This class uses `SimWrapper` instances to efficiently organize and control the entities in the co-simulation environment.  

Looking forward to feedback :)

### CODE REVIEW

**Comment by marvin-steinke** [comment]
> The cosim_example looks pretty nice and easy to use and I really like the concept. So thats great! However, making new cosim components seems to be rather tedious as you have to write three new subclasses for every component (probably also impossible for someone who has never used Mosaic). Maybe we can find a way to somehow join the SimWrapper with the VessimSimulator to get rid of some complexity there?? Also, I think we have to have a look at what we want to do with the Storage. I dont really like that it is part of the coordinator here, but we can discuss that later.

I agree, for someone who wants to write a new vessim sim, the current implementation procedure is too complex. I will think of alternatives.

**Review by birnbaum — COMMENTED** [review]
yes let's maybe talk about the draft next meeting, I have some issues with the current version: There is a new abstraction layer, lot's of new boilerplate classes and an additional 200 lines of code only to reduce cosim_example.py from 100 zu 80 LOC. Users still perform exactly the same actions in your new API. Why do I still need to manually start all components? How would you simulate multiple energy systems in one simulation now? While it was cumbersome before, it seems to be impossible now.

Let's agree on a clean interface first instead of implementing everything directly :)

**Comment by birnbaum** [comment]
a suggestion for a minimal interface could be something like:

```python
environment = vessim.Environment()
    
microgrid = Microgrid(
    prosumers=[
        ComputingSystem(...),
        TimeSeriesApi(...),  # solar
    ],
    storage=SimpleBattery(...),
    storage_policy=DefaultStoragePolicy(),
    grid_signals=dict(carbon_intensity=TimeSeriesApi(), price=TimeSeriesApi()),
    ecovisor=Ecovisor(),
    monitor=True,
)

environment.add(microgrid)
environment.run()
```

**Comment by marvin-steinke** [comment]
> a suggestion for a minimal interface could be something like:
> 
> ```python
> environment = vessim.Environment()
>     
> microgrid = Microgrid(
>     prosumers=[
>         ComputingSystem(...),
>         TimeSeriesApi(...),  # solar
>     ],
>     storage=SimpleBattery(...),
>     storage_policy=DefaultStoragePolicy(),
>     grid_signals=dict(carbon_intensity=TimeSeriesApi(), price=TimeSeriesApi()),
>     ecovisor=Ecovisor(),
>     monitor=True,
> )
> 
> environment.add(microgrid)
> environment.run()
> ```

For our abstraction, are we assuming that one Mosaik factory only manages one simulation? In our current simulatiors we give factories and models different parameters which in practice we do not use.

**Comment by birnbaum** [comment]
so I'd say each vessim.Environment has one Mosaik co-simulation under the hood. This co-simulation should then be able to simulate multiple microgrids where each microgrid can host a REST API. Does this make sense?

**Comment by marvin-steinke** [comment]
I had some thoughts on the scenario interface. Let me know what you think. If this is the direction we would like to head into, I will work out, how the simulations themselves can be designed user friendly and how this can be abstracted away in base classes etc.

## Sim Instantiation

We want multiple simulators of the same type e.g. microgrids to be managed by the very same mosaik_api.Simulator obj under the hood. We currently handle this by rawly instantiating a factory (mosaik_api.Simulator) and then using this factory to spawn an entity:

```python
carbon_api_sim = world.start(
    "CarbonApi", sim_start=SIM_START, carbon_api=TimeSeriesApi(
        actual=load_carbon_data())
)
carbon_api_de = carbon_api_sim.CarbonApi(zone="DE")

solar_sim = world.start("Generator", sim_start=SIM_START)
solar = solar_sim.Generator(
    generator=TimeSeriesApi(actual=load_solar_data(sqm=0.4 * 0.5))
)
```

This is kinda confusing at first and a user without knowledge of Mosaik does not know what is going on. Also, initiating a simple simulation entity often does not need configuration for its factory, especially when there is only one entity to be used (more on that in vessim enviroment section).

-> We could merge both together into one call like:

```python
carbon_api = CarbonApi(
    sim_start=SIM_START,
    carbon_api=TimeSeriesApi(actual=load_carbon_data()),
    zone="DE"
)

solar = Generator(
    sim_start=SIM_START,
    generator=TimeSeriesApi(actual=load_solar_data(sqm=0.4 * 0.5))
)
```
(The sim name is implicit for now.) and if we want multiple entities within the same mosaik_api.Simulator:
```python
zones = ["DE", "ES", "FR", "NL"]
carbon_api = [
    CarbonApi(
        sim_start=SIM_START,
        carbon_api=TimeSeriesApi(actual=load_carbon_data()),
        zone=zone
    )
    for zone in zones
]
```
We assume here that vessim simulators with the same factory args like `sim_start` or `step_size` are mapped to the same mosaik_api.Simulator obj. If these factory args differ, a new mosaik_api.Simulator obj is created and entities of the same vessim simulator are not within the same mosaik_api.Simulator obj. I do not think it would be sensible for most use cases but I still think is should be possible to create two distinct mosaik_api.Simulator objs with the same vessim simulator i.e. the same factory args. Maybe this could be solved with a simple extra optional arg like:
```python
carbon_ap1 = CarbonApi(
    sim_start=SIM_START,
    carbon_api=TimeSeriesApi(actual=load_carbon_data()),
    zone="DE"
    group="group1"
)

carbon_ap2 = CarbonApi(
    sim_start=SIM_START,
    carbon_api=TimeSeriesApi(actual=load_carbon_data()),
    zone="DE",
    group="group2"
)
```

### Vessim Environment

The vessim Environment should coordinate the vessim simulators and hold information like `sim_start`, `duration`, `rt_factor` and (maybe?) `standard_step_size` which the simulations should also be able to access. This eliminates the need to specify factory args that most simulators share:
```python
env = vessim.Environment(sim_start, duration, rt_factor, step_size)
carbon_ap1 = CarbonApi(
    # no more sim_start
    carbon_api=TimeSeriesApi(actual=load_carbon_data()),
    zone="DE"
    # specify environment
    env=env
)
env.run()
```

## Sim Connections 

The connections can either be made directly from the main() like we currently do, just that we wrap Mosaik's connect function for simplification, or we could pass the sims as args to other sims like in Philipp's suggestion. In the latter case, the sims could then call the connect function themselves from the vessim environment, and abstract some of the complexity we see currently in the scenario. New user might have problems looking at the scenario, trying to decipher what the variables mean in `world.connect(computing_system, monitor, ("p", "p_computing_system"))`. I think this would also look nicer overall as well.

### Monitor

I like the `monitor` flag from philipps suggestion and think we should keep it. Currently, we basically connect every simulator to the Monitor and I don't think that's necessary.
```python
monitor = Monitor(out_path=result_csv)
env = vessim.Environment(sim_start, duration, rt_factor, step_size, monitor)
carbon_ap1 = CarbonApi(
    carbon_api=TimeSeriesApi(actual=load_carbon_data()),
    zone="DE"
    env=env
    monitor=True
)
env.run()
```

**Pull request closed without merging**
